version: "3.8"

services:
   postgres:
      image: postgres:latest
      container_name: chronoscontainer
      restart: always
      environment:
         POSTGRES_USER: chronosadmin
         POSTGRES_PASSWORD: 7833fwcQu0Ha
         POSTGRES_DB: chronosbd
      ports:
         - "5433:5432"
      volumes:
         - chronos_postgres_data_novo:/var/lib/postgresql/data

volumes:
   chronos_postgres_data_novo:
